apiVersion: argoproj.io/v1alpha1 
kind: ApplicationSet
metadata:
  name: super-octo-infra
  namespace: openshift-gitops 
spec:
  generators:
  # - git:
  #     repoURL: "https://github.com/gmodzelewski/super-duper-octo-infra"
  #     revision: main
  #     files:
  #     - path: "stages/**/config.json"
  - list:
      elements:
        - stage: dev
          namespace: super-octo-infra  
  template:
    metadata:
      name: 'super-octo-infra-{{stage}}-app'
    spec:
      project: default 
      source:
        repoURL: "https://github.com/gmodzelewski/super-duper-octo-infra"
        path: neuanfang/super-octo-infra
        helm:
          # valueFiles: 
          # - values.{{cluster}}.yaml
          parameters:
          - name: feature_flag_workshop_camelk
            value: "true"
          # - name: feature_flag_workshop_gitops
          #   value: "false"
          # - name: feature_flag_workshop_mta
          #   value: "false"
      destination:
        server: 'https://kubernetes.default.svc' 
        namespace: '{{namespace}}'
      syncPolicy: 
        automated:
          selfHeal: true
          prune: true
        syncOptions:
        - CreateNamespace=true
      ignoreDifferences:
      - group: image.openshift.io
        kind: ImageStream
        jsonPointers:
        - /spec/tags
      - group: apps.openshift.io
        kind: DeploymentConfig
        jsonPointers:
        - /spec/template/spec/containers/0/image