apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    enableUserWorkload: true 
    prometheusK8s:
      retention: 24h
      retentionSize: 10GB
      volumeClaimTemplate:
        spec:
          storageClassName: managed-nfs-storage
          volumeMode: Filesystem
          resources:
            requests:
              storage: 70Gi