apiVersion: v1
kind: List
metadata:
  resourceVersion: ""
items:
- apiVersion: cert-manager.io/v1
  kind: ClusterIssuer
  metadata:
    name: letsencrypt-production
  spec:
    acme:
      email: modzelewski.georg@gmail.com
      preferredChain: ""
      privateKeySecretRef:
        name: issuer-letsencrypt
      server: https://acme-v02.api.letsencrypt.org/directory
      solvers:
      - http01:
          ingress:
            class: openshift-default
- apiVersion: cert-manager.io/v1
  kind: ClusterIssuer
  metadata:
    name: letsencrypt-production-istio
  spec:
    acme:
      email: modzelewski.georg@gmail.com
      preferredChain: ""
      privateKeySecretRef:
        name: issuer-letsencrypt-istio
      server: https://acme-v02.api.letsencrypt.org/directory
      solvers:
      - http01:
          ingress:
            class: istio
- apiVersion: cert-manager.io/v1
  kind: ClusterIssuer
  metadata:
    name: letsencrypt-staging
  spec:
    acme:
      email: modzelewski.georg@gmail.com
      preferredChain: ""
      privateKeySecretRef:
        name: issuer-letsencrypt-staging
      server: https://acme-staging-v02.api.letsencrypt.org/directory
      solvers:
      - http01:
          ingress: {}
- apiVersion: cert-manager.io/v1
  kind: ClusterIssuer
  metadata:
    name: letsencrypt-staging-istio
  spec:
    acme:
      email: modzelewski.georg@gmail.com
      preferredChain: ""
      privateKeySecretRef:
        name: issuer-letsencrypt-stagiging-istio
      server: https://acme-staging-v02.api.letsencrypt.org/directory
      solvers:
      - http01:
          ingress:
            class: istio
