apiVersion: v1
kind: Namespace
metadata:
  name: cert-utils-operator
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-cert-manager-operator
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-distributed-tracing
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-logging
---
apiVersion: v1
kind: Namespace
metadata:
  name: konveyor-tackle
