{{- if .Values.feature_flag_workshop_camelk }}
apiVersion: org.eclipse.che/v2
kind: CheCluster
metadata:
  name: devspaces
  namespace: openshift-operators
spec:
  components:
    cheServer:
      debug: false
      logLevel: INFO
    dashboard:
      logLevel: ERROR
    imagePuller:
      enable: true
      spec:
        images: "camelk-developer-image=quay.io/modzelewski/camelk-developer-image;che-theia=quay.io/eclipse/che-theia:next"
    metrics:
      enable: true
    pluginRegistry:
      openVSXURL: https://open-vsx.org
  devEnvironments:
    containerBuildConfiguration:
      openShiftSecurityContextConstraint: container-build
    defaultNamespace:
      autoProvision: true
      template: devspaces-<username>
    maxNumberOfRunningWorkspacesPerUser: 3
    maxNumberOfWorkspacesPerUser: 5
    secondsOfInactivityBeforeIdling: 1800
    secondsOfRunBeforeIdling: -1
    startTimeoutSeconds: 300
    storage:
      pvcStrategy: per-user
  networking:
    auth:
      gateway:
        configLabels:
          app: che
          component: che-gateway-config
        kubeRbacProxy:
          logLevel: 0
        oAuthProxy:
          cookieExpireSeconds: 86400
        traefik:
          logLevel: INFO
{{- end }}